# PostgreSQL 이미지 사용
FROM postgres:15.1-alpine

# 메타데이터 추가
LABEL version="1.0.0" 
LABEL maintainer="kang san"

# 초기화 스크립트 디렉토리 설정
WORKDIR /docker-entrypoint-initdb.d/

# 초기화 SQL 파일 복사
COPY postgres.d/init.sql ./

# 실행 권한 부여
RUN chmod 755 ./init.sql