name: Deploy Gateway Service

on:
  push:
    branches: [ main, master ]
    paths:
      - 'micro-services/gateway/**'
      - '.github/workflows/gateway-deploy.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'micro-services/gateway/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
      - name: Install dependencies
        working-directory: micro-services/gateway
        run: npm ci
        
      - name: Build application
        working-directory: micro-services/gateway
        run: npm run build
        
      # 테스트가 있다면 추가
      # - name: Run tests
      #   working-directory: micro-services/gateway
      #   run: npm test
      
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: micro-services/gateway/dist
          key: ${{ runner.os }}-gateway-build-${{ github.sha }}
          
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: micro-services/gateway/dist
          key: ${{ runner.os }}-gateway-build-${{ github.sha }}
          
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SERVER_PORT || 22 }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy gateway service to Server
        run: |
          rsync -avz --delete \
            -e "ssh -p ${{ secrets.SERVER_PORT || 22 }}" \
            --exclude='node_modules/' \
            micro-services/gateway/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}/micro-services/gateway/
            
      - name: Execute deployment script
        run: |
          ssh -p ${{ secrets.SERVER_PORT || 22 }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd ${{ secrets.DEPLOY_PATH }}/micro-services/gateway && bash deploy.sh"